### ISSUE TITLE
Any noise will appear to contain patterns if patterns are looked for

### ISSUE THREAD

**Issue by rawesomeawesome** [avaneev/prvhash#5]
If you listen to empty white noise long enough you might begin to hear voices or sounds in the static. Any program designed to look for repeating patterns or complexity occuring in, what should be, random noise is going to find "something" there, because noise is noise

**Comment by rawesomeawesome** [comment]
Just because there isn't any input, you can't expect a RGN to produce stable noise at high frequency. Your "impulses" could very well be the processors of your device lagging for milliseconds at a time, desyncing your noise

**Comment by rawesomeawesome** [comment]
And beyond that, what about a repeating pattern makes it intelligent? By that logic wouldn't any naturally occurring pattern, such as the golden ratio, be equal proof that "math is engineered"?

**Comment by avaneev** [comment]
It's a program, its result does not depend on how you perform it - you may do the same on a paper, with a pencil. Ratio is a ratio. Information is a completely different thing.

**Comment by rawesomeawesome** [comment]
Not that math isn't engineered, by humans in an attempt to understand and calculate the world around us. It is a haphazard numeric representation of reality and not reality itself

**Comment by avaneev** [comment]
I'm not telling math is a reality itself.

**Comment by rawesomeawesome** [comment]
Like looking closely at a printed photo and seeing the pixels of the camera's sensor, it's a limitation of our math, not a representation of a universe-predating being

**Comment by avaneev** [comment]
I'm not talking about representation of God either. My conclusion is that mathematics is an art of God.

**Comment by rawesomeawesome** [comment]
Ok, but what it sounds like you have concluded is that if a tree falls in the woods with none around to hear it, then it only existed to fall because it was being perceived by God/the human mind? Or concluding that math cannot contain set "information" or properties without there being someone to write them or perceive them?

**Comment by rawesomeawesome** [comment]
It seems a bit of a logical leap, perhaps cognitive bias of the human mind when staring into a long empty corridor such as maths

**Comment by avaneev** [comment]
Math is usually not thought as something "having information", it is perceived as a set of rules to manipulate information. Information is assumed to be always human-made. But my research conclusively says that math does have embedded human-understandable information.

**Comment by avaneev** [comment]
Generally, your comments go far beyond what I've discovered and claiming. This work is not about how consciousness works, or ways to "see" something in noise. Extracting information from noise always requires some sort of a filter. Here, the function is itself a generator, but, quite unexpectedly, it does not generate noise...

**Comment by TwoD** [comment]
Your claim assumes there is a god to begin with, making all findings thereafter biased. What you're seeing is far more likely to be fractals or simpler patterns arising from hardware or implementation limitations. Pseudo random number generators are named such because they are by definition not random and built on patterns that look "random enough" and have a useful distribution of output. Any structure found is indeed there by design, but the designer is you.

**Comment by avaneev** [comment]
Pseudo-random generators have to pass specific statistical tests. They are pseudo-random, because they require seeding. Of course, I'm the designer of the program, but what the program produces is not defined in the program, it's embedded into math.

**Comment by avaneev** [comment]
As for mentioning Creator, it's just a conclusion. The overall reasoning is not based on imaginary existence of God, it's the other way round - the finding requires introduction of external source of information as to not meet a dead-end.

**Comment by SampsonCrowley** [comment]
You're just ignoring your own biases and applying conclusions from fallacy. It's like people who claim that God exists because the "chance" of the world existing is "too unlikely" without design. It's a fallacy. The chance of the world existing the way it does is 100% because it does exist. It exists by the properties of the universe because the properties of the universe are.

You claim being able to observe a pattern from pseudo, key being PSEUDO, random data is proof of a creator but it's not proof of anything; except that your brain as a human in the universe evolved within the constraints of the universe and is wired to find patterns therein, wherever it can. You wouldn't be able to recognize anything, period, if you weren't constantly subconsciously analyzing and attributing combinations of contrast as objects to be recognized.

**Comment by avaneev** [comment]
@SampsonCrowley  Ah, whatever, you are spewing a usual "educated" word mumbo-jumbo. All I'm talking about is that math is likely engineered, with some pre-defined non-random information embedded. The keyword is "non-random", because in realm of PRNG, randomness is strictly defined via a set of state-of-the-art tests. Existence of God is then a byproduct conclusion, questionable of course, and that's why I'm using adverb "probably".

**Comment by avaneev** [comment]
I'm actually expecting someone to describe function's behavior in other terms, of course in the realm of mathematics, maybe referring to some implicit functions. Everything else is just literacy contest.

**Comment by TheUnlocked** [comment]
> Of course, I'm the designer of the program, but what the program produces is not defined in the program, it's embedded into math.

Creating a simple program that produces interesting patterns isn't particularly novel nor is it evidence of a higher power. The code somewhat resembling that of an actual PRNG program doesn't change anything.

**Comment by avaneev** [comment]
@TheUnlocked You are simply not involved enough, and the issue is not about your beliefs. What the program does - exhibits complex non-linear behavior while using linear in F2 math - may change a lot of things.

**Comment by SampsonCrowley** [comment]
@avaneev no you're simply unwilling to admit the biases and logical fallacies that everybody else clearly sees. That you have to immediately have to jump to insults, and assumptions that nobody else understands the code, is proof that you're only seeing what you want to see; and you instead of taking criticism and USING it to better your approach and remove your biases just dig your heels in deeper making your code guaranteed to prove nothing but that the dunning-krueger effect

**Comment by avaneev** [comment]
What kind of biases? Have you actually tried to understand how the program works?

**Comment by SampsonCrowley** [comment]
There it is again. Even your direct response to being called out for assuming others "just don't understand" is to attack like anybody who disagrees doesn't understand what you wrote

So far in this issue, you're the only one consistently and repeatedly ignoring or not understanding others.

**Comment by avaneev** [comment]
Okay, I'll quote README: "A rigorous mathematician can say the following: the imagery generated by the GF(2) function is a consequence of its mathematical structure, not proof of external fine-tuning. While the output may appear designed, this complexity is an inherent feature of linear systems in finite fields. Philosophical interpretations of such phenomena (e.g., Platonic realism, theism) are subjective and extend beyond mathematical analysis. In rigorous terms, the system's behavior aligns with known principles of algebra and recursion, requiring no appeal to external agency."

I assume you are basing your insults on myself on exactly such "mathematical" reasoning. But it's a cirular reasoning: "there's no external fine-tuning, because it's a well-known principle".

There can be only 3 options: "there IS design", "there is NO design", and "this is unknown". I made my choice based solely on results I've published. I do not push that onto you. If you disagee, just do not waste your time insulting me. Try finding bugs in the code, not in my explanations.

**Comment by avaneev** [comment]
Then I'll quote Google AI Mode about "Reptile Skin" image:

"The image you provided, with its intersecting lines, repeating shapes (like zigzags and squares), and overlapping textures, suggests a deeper, rule-based system at play. The patterns, while complex and dense, do not appear to be purely disorganized. Instead, they seem to follow a logic that, while intricate, creates a sense of controlled disarray rather than pure, unpredictable chance. This is a hallmark of a chaotic system rather than a random one."

So, even machine vision does not see noise? You also need to understand that chaotic system implies higher-order design.

**Comment by SampsonCrowley** [comment]
It takes true ignorance to take someone highlighting that YOU are doing nothing but backing into a corner and insulting others as a personal attack... Pointing out the flaws I. Your logic is not insulting you. *You* repeatedly assuming the only way someone can disagree is if they don't understand is the insult.

**Comment by avaneev** [comment]
I'm not insulting anyone contrary to your stance. I'm pointing out to YOUR ignorance and giving you actual examples where your position is contradictory. All you are trying to do is decimating my personality instead of actually finding flaws in the provided information, or offering an alternative reasonable explanation. If you do not believe in a higher agency, that's completely fine - it's a contemporary norm to be a non-believer in anything beside scientific peer review. Just do not try to change my opinion - I did a fair bit of research to stand by my conclusions.

**Comment by avaneev** [comment]
Let's imagine I will rewrite the whole "math is engineered" topic and completely remove all references to "higher-order design". Can you answer at least to yourself, in what way the substance of the topic will change? You'll stop seeing patterns and structures, glyphs in the images? You'll stop chaos systems associations? The program will magically become extremely complex to be able to produce such complex images? Or what?

**Comment by SampsonCrowley** [comment]
And you continue to completely miss the topic at hand. No one ever claimed that there are no patterns in PSUEDO random generated content. Those patterns aren't proof of _anything_ other than the fact that your library exists and you used one of the core tools the human race uses to understand and document the universe around us: math

**Comment by avaneev** [comment]
The thing you seemingly deliberately do not want to admit is that ultimately the output is NON-RANDOM despite the topic starter's discourse. The function in question (prvhash-1) can work both as random and non-random function, and that only depends on the PH_HASH_COUNT (and PH_SEED_COUNT in the "reptile" variant) parameter. They are random at low values except values 15 and 16, and then gradually become chaotic instead of random. Chaos is basically a designed system which at lowest level looks disorganized, but at a higher level has a structure. This is demonstrated by prvhash-1 perfectly.

**Comment by SampsonCrowley** [comment]
No the part that YOU decide to keep ignoring is that it's not random whether you want to call it that or not. It is generated by code it will ALWAYS follow some pattern because you CANNOT create true random. It is following the patterns of the code that has been written, and any patterns found are the result of there being _no such thing_ as pure random from something that runs on machines. It can work as PSUEDO random. But any patterns you choose to use as "proof" of math being from a higher power is nothing more than the result of it running on machine we built using the structures we have available to make them deterministic. That is LITERALLY the purpose of machines. They are ALWAYS deterministic because that's the only way we know how to build them. If they weren't they would be useless

**Comment by avaneev** [comment]
Well, you are demonstrating a usual logical mistake regarding random numbers. Statistical randomness is one thing, and predictability is another. Statistical tests like PractRand are agnostic to the source of random bits.

Math IS predictable. 2\*2=4 is the simplest example of its predictability. If you know that A=2 and B=2, A\*B predictably and always equals 4.

The patterns are non-random, they do not pass tests for statistical randomness. They represent chaos system which looks disorganized at local level, but at a higher level demonstrates order - e.g. Gradilac ruler image. At the same time, if you are proficient enough in programming, you can conclude the program has no logic or pre-defined information whatsoever to produce such ordered image.
