### ISSUE TITLE
Christians have already argued this about fractals 

### ISSUE THREAD

**Issue by Herteby** [avaneev/prvhash#6]
https://youtu.be/taKaFUNJ6Ec

I can kind of understand people finding the Mandelbrot set etc. pretty spooky, how these beautiful infinitely detailed structures are "hidden" behind simple formulas. In what way are your examples more profound?

**Comment by Erudition** [comment]
My understanding from the document is that, unlike other "math art" that can be generated by specific formulas (Fibbonacci formulas, Serpinski triangles, Mandelbrot sets) with chosen inputs and starting values, the patterns demonstrated here are not formulaic in origin. They are produced from plain old randomness, yet they are clearly not always mere random noise, to the human mind, in output. 

The generator also produces top-notch randomness as well, though. Without any fixed constants or entropy-reducing formulas involved, how can the same generator produce high-quality chaos and also high-quality order?

The Mandelbrot fractals, as I understand it, are an example of high-quality order, produced by a formula that was chosen/discovered to do so. The order presented here was not produced from a formula, though. And we can find more patterns and fractals by different rules than just one.

The way I see it, if we were all in a simulation, it makes sense that there would be involved both Mathematical rules and something like a PRNG. This is the way we design video games, anyway. We're we'll underway to exploring the rules, but there is still the source of randomness (unpredictability) under it all that makes e.g. quantum physics so baffling. That would be the PRNG. It has some seed value when generating our universe; perhaps there are other simulations with other seed values, perhaps infinite.

But what if humans discovered a PRNG that doesn't need a seed? It can produce chaos from order and order from chaos using nothing but the existing universal rules of math. Well, that seems to be the case here. But that's not how pure functions work... so where is the seed of entropy coming from?

In essence, I figure that if we were to discover the seed that's fed to the function that generated our universe, this is how we would do it! The generator here pulls randomness out of nowhere, so it must be built into the universe itself - which to us means "math itself". We've found the seed value of all seed values (pi, e, and other mathematical constants are theoretically derived from it) and that means "someone" must have given us that particular seed value - perhaps those running the simulation - and engineered the rules (of our particular math) around it.

To be clear, Christians also believe that the **JudeoChristian God** exists, a "he" who is omniscient, omnipotent, benevolent, omnipresent, and more or less accurately described by ancient human textbooks. Though I'm sure they wouldn't mind people jumping to that conclusion, it's a far cry from the mere assertion that something that could be described as a "creator" exists. (The creator could also be e.g. Rick, and we could all be living inside his car battery... :P )

**Comment by avaneev** [comment]
Your flow of reason seems plausible to me. Yes, the whole problem is: where the ordered patterns come from given the function consists of just 3 "delay lines" (in DSP math terms) which just delay and shuffle their own output. There's no seed input from the user (starts from all-zeros state), no internal constants to tweak (isolated 0 and 1 bits have no entropy, they are not information).

On another note, please do not use "JudeoChristian" attribution. Judaism and Christianity are different religions, which are based on different premises, and are only sharing some vague common roots. The Gods are different as well, because Judaism does not accept Christ as an avatar of unified God. Not that this is overly important to me, but it just demonstrates we should not be making any references to religion here. I'm more comfortable using "Higher intelligence" term myself, or just "external entropy source".

**Comment by avaneev** [comment]
On Mandelbrot sets, I'll note that: if I'm not mistaken, it does need sinusoidal functions to be constructed. As I've discovered (this is mentioned at the project page), a sinewave oscillator can be used as PRNG as well. So, a sinusoid much like the PI number itself, is a source of entropy as well, but they are harder to be perceived as "external", because PI is a RATIO between circle's circumference and its diameter.

**Comment by avaneev** [comment]
I've probably noted a "dip" in mathematics. The uncountable numbers are based on the set theory and as example a number PI is mentioned. But this refers to set of digits in the number PI. There can be uncountable numbers "as is" without relation to counting in set theory sense. I would call them "unimaginable numbers".
